In [3]:
import requests # request img from web
import shutil # save img locally
import time
import os 
import numpy as np
from tensorflow.keras.models import load_model
from keras.preprocessing import image
import requests
import json
import matplotlib.pyplot as plt

In [4]:
from tensorflow.keras.models import load_model


classifier = load_model('CNNModel.hdf5')

In [5]:
def water_dust(image_path):
    li=['clean','dirty']
    new_img = image.load_img(image_path, target_size=(224, 224))
    img = image.img_to_array(new_img)
    img = np.expand_dims(img, axis=0)
    img = img/255

    print("Detected:")
    print('\n')
    prediction = classifier.predict(img)
    print(prediction)
    d = prediction.flatten()
    print(d)
    j = d.max()
    print(j)
    for index,item in enumerate(d):
        print(index,item)
        if item == j:
            class_name = li[index]
    print(class_name)
    
   
    return class_name

In [6]:
water_dust('IMG_8126.JPG')

Detected:


1/1 [==============================] - 1s 929ms/step
[[0. 1.]]
[0. 1.]
1.0
0 0.0
1 1.0
dirty


'dirty'

In [7]:
water_dust('IMG_8043.JPG')

Detected:


1/1 [==============================] - 0s 108ms/step
[[0. 1.]]
[0. 1.]
1.0
0 0.0
1 1.0
dirty


'dirty'

In [8]:
def download():
    url = 'http://192.168.4.3/capture'
    file_name = '1.png'

    res = requests.get(url, stream = True)

    if res.status_code == 200:
        with open(file_name,'wb') as f:
            shutil.copyfileobj(res.raw, f)
        print('Image sucessfully Downloaded: ',file_name)
    else:
        print('Image Couldn\'t be retrieved')

In [9]:
download()

Image sucessfully Downloaded:  1.png


In [10]:

while True:
    download()
    res=water_dust('1.png')
    #res=prediction()
    print(res)
    if res=='dirty':
        print('garbage')
        requests.get("http://192.168.4.1/f")
        requests.get("http://192.168.4.1/c")
        time.sleep(3)
        requests.get("http://192.168.4.1/b")
        requests.get("http://192.168.4.1/d")
        time.sleep(3)
        requests.get("http://192.168.4.1/s")
        
    else:
        print('no garbage')
        requests.get("http://192.168.4.1/l")
        time.sleep(2)
        requests.get("http://192.168.4.1/s")
    time.sleep(2)

Image sucessfully Downloaded:  1.png
Detected:


1/1 [==============================] - 0s 117ms/step
[[0. 1.]]
[0. 1.]
1.0
0 0.0
1 1.0
dirty
dirty
garbage
Image sucessfully Downloaded:  1.png
Detected:


1/1 [==============================] - 0s 142ms/step
[[0. 1.]]
[0. 1.]
1.0
0 0.0
1 1.0
dirty
dirty
garbage
Image sucessfully Downloaded:  1.png
Detected:


1/1 [==============================] - 0s 106ms/step
[[5.6067843e-35 1.0000000e+00]]
[5.6067843e-35 1.0000000e+00]
1.0
0 5.6067843e-35
1 1.0
dirty
dirty
garbage
Image sucessfully Downloaded:  1.png
Detected:


1/1 [==============================] - 0s 147ms/step
[[0. 1.]]
[0. 1.]
1.0
0 0.0
1 1.0
dirty
dirty
garbage
Image sucessfully Downloaded:  1.png
Detected:


1/1 [==============================] - 0s 176ms/step
[[0. 1.]]
[0. 1.]
1.0
0 0.0
1 1.0
dirty
dirty
garbage
Image sucessfully Downloaded:  1.png
Detected:


1/1 [==============================] - 0s 128ms/step
[[0. 1.]]
[0. 1.]
1.0
0 0.0
1 1.0
dirty
dirty
garbage
Image suce

ConnectTimeout: HTTPConnectionPool(host='192.168.4.3', port=80): Max retries exceeded with url: /capture (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000025880109190>, 'Connection to 192.168.4.3 timed out. (connect timeout=None)'))

In [ ]:
download()